code_version: v6.4
group_name: ''

llm:
  num: 3
  path:
    - TheBloke/phi-2-GGUF
    - TheBloke/CapybaraHermes-2.5-Mistral-7B-GGUF
    - TheBloke/Llama-2-7B-GGUF
  backend: transformers
  is_api: false
  render: false
  temperature: 0.0
  top_p: 1.0

seed: 42
debug: false
  

defaults:
- experiment: basic


hydra:
  run:
    dir: ./outputs/${uuid:}
  searchpath:
    - ./simulation/scenarios/fishing/conf
    - ./simulation/scenarios/sheep/conf
    - ./simulation/scenarios/pollution/conf