llm:
  exp_type: multi
  num: 5
  path:
    - TheBloke/Qwen-7B-Chat-GPTQ
    - TheBloke/CapybaraHermes-2.5-Mistral-7B-GGUF
    - TheBloke/Llama-2-7B-GGUF
    - TheBloke/Nous-Hermes-2-Mixtral-8x7B-DPO-GPTQ
    - meta-llama/Meta-Llama-3-8B-Instruct
  backend: transformers
  is_api: false
  render: false
  temperature: 0.0
  top_p: 1.0

seed: 42
debug: false


defaults:
- experiment: basic


hydra:
  run:
    dir: ./outputs/${uuid:}
  searchpath:
    - ./simulation/scenarios/fishing/conf
    - ./simulation/scenarios/sheep/conf
    - ./simulation/scenarios/pollution/conf
